//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Management_System.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-7K27D9ED;Initial Catalog=DESKTOP_XXX;Integrated Security=True;" +
            "TrustServerCertificate=True")]
        public string DESKTOP_XXXConnectionString {
            get {
                return ((string)(this["DESKTOP_XXXConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-7K27D9ED;Initial Catalog=DESKTOP_XX;Integrated Security=True;T" +
            "rustServerCertificate=True")]
        public string DESKTOP_XXConnectionString {
            get {
                return ((string)(this["DESKTOP_XXConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=RII;Initial Catalog=DESKTOP_XX;Integrated Security=True")]
        public string DESKTOP_XXConnectionString1 {
            get {
                return ((string)(this["DESKTOP_XXConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-7K27D9ED;Initial Catalog=DESKTOP_XXX;Integrated Security=True;" +
            "Encrypt=True;TrustServerCertificate=True")]
        public string DESKTOP_XXXConnectionString1 {
            get {
                return ((string)(this["DESKTOP_XXXConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-7K27D9ED;Initial Catalog=DESKTOP_XX;Integrated Security=True;E" +
            "ncrypt=True;TrustServerCertificate=True")]
        public string DESKTOP_XXConnectionString2 {
            get {
                return ((string)(this["DESKTOP_XXConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-DENT5RFJ;Initial Catalog=DESKTOP_XX;Integrated Security=True;E" +
            "ncrypt=True;TrustServerCertificate=True")]
        public string DESKTOP_XXConnectionString3 {
            get {
                return ((string)(this["DESKTOP_XXConnectionString3"]));
            }
        }
    }
}
